name: lomiri-ui-toolkit-core20
version: "latest"
summary: A convergent UI toolkit for all formfactors
description: |
  Lomiri is the continuation of the Unity8 effors by Canonical Ltd.
compression: lzo
grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

slots:
  lomiri-ui-toolkit:
    content: lomiri-ui-toolkit
    interface: content
    read:
      - $SNAP

parts:
  qtsystems:
    plugin: qmake
    qmake-project-file: qtsystems.pro
    source: https://github.com/qt/qtsystems.git
    source-commit: e3332ee38d27a134cef6621fdaf36687af1b6f4a
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtbase5-private-dev
        - qtdeclarative5-dev
    stage-packages:
        - libdouble-conversion3
        - libevdev2
        - libfreetype6
        - libgl1
        - libglvnd0
        - libglx0
        - libgraphite2-3
        - libharfbuzz0b
        - libicu66
        - libpcre2-16-0
        - libpng16-16
        - libqt5core5a
        - libqt5dbus5
        - libqt5gui5
        - libqt5network5
        - libqt5qml5
        - libqt5quick5
        - libqt5sql5
        - libx11-6
        - libxau6
        - libxcb1
        - libxdmcp6
  qtfeedback:
    plugin: qmake
    after: [ qtsystems ]
    qmake-project-file: qtfeedback.pro
    source: https://github.com/qt/qtfeedback.git
    source-commit: a14bd0bb1373cde86e09e3619fb9dc70f34c71f2
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtbase5-private-dev
  qtpim:
    after: [ qtfeedback ]
    plugin: qmake
    qmake-project-file: qtpim.pro
    source: https://github.com/qt/qtpim.git
    source-commit: 8fec622c186d254bc9750606d54c32670a9046a5
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtbase5-private-dev
    stage-packages:
        - libqt5widgets5
  suru-icons:
    after: [ qtpim ]
    plugin: nil
    source: https://gitlab.com/ubports/core/suru-icon-theme.git
    source-branch: main
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons
      cp -a $SNAPCRAFT_PART_SRC/suru $SNAPCRAFT_PART_INSTALL/usr/share/icons/
  lomiri-ui-toolkit:
    plugin: qmake
    after: [ suru-icons ]
    qmake-project-file: lomiri-sdk.pro
    qmake-parameters:
        - CONFIG+=ubuntu-uitk-compat
    source: https://gitlab.com/ubports/core/lomiri-ui-toolkit.git
    source-branch: main
    override-build: |
      rm -rf $SNAPCRAFT_PART_SRC/examples || true
      sed -i "s/ po / /g" $SNAPCRAFT_PART_SRC/lomiri-sdk.pro
      cd $SNAPCRAFT_PART_BUILD
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - libxi-dev
        - qtbase5-private-dev
        - qtdeclarative5-private-dev
        - qml-module-qtquick2
        - qml-module-qtquick-window2
        - qml-module-qtquick-layouts
        - qml-module-qtgraphicaleffects
        - qml-module-qttest
    stage-packages:
        - ttf-ubuntu-font-family
        - yaru-theme-icon
        - libbluetooth3
        - liblttng-ust0
        - libnuma1
        - liburcu6
        - libdouble-conversion3
        - libegl1
        - libevdev2
        - libfreetype6
        - libgl1
        - libglvnd0
        - libglx0
        - libgraphite2-3
        - libharfbuzz0b
        - libicu66
        - libpcre2-16-0
        - libpng16-16
        - libqt5core5a
        - libqt5dbus5
        - libqt5gui5
        - libqt5network5
        - libqt5qml5
        - libqt5quick5
        - libqt5test5
        - libqt5widgets5
        - libx11-6
        - libxau6
        - libxcb1
        - libxdmcp6
        - libxext6
        - libxi6
  qt-setup:
    after: [ lomiri-ui-toolkit ]
    source: https://github.com/snapcore/snapcraft-desktop-integration.git
    plugin: nil
    override-build: |
      cd qt-framework
      make PLATFORM_PLUG=desktop DESTDIR=$SNAPCRAFT_PART_INSTALL install
    stage:
      - command-chain
